import { db } from "@/lib/db"
import { getClubContext, error } from "@/lib/server-auth"

function csvEscape(s: string): string {
  if (!s) return ""
  if (/[",\n\r]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`
  }
  return s
}

function fmtDate(d: Date): string {
  // YYYY-MM-DD for stable CSV dates
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, "0")
  const day = String(d.getDate()).padStart(2, "0")
  return `${y}-${m}-${day}`
}

function fmtDateReadable(d: Date): string {
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  })
}

function fmtDateTime(d: Date): string {
  return d.toISOString()
}

function fmtDateTimeReadable(d: Date): string {
  return d.toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  })
}

function htmlEscape(s: string): string {
  return (s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;")
}

/**
 * GET /api/clubs/[clubId]/hours/export
 *
 * By default returns a styled, printable HTML document of the current user's
 * APPROVED service hours — open in the browser, then "Print → Save as PDF"
 * for a clean, professional record. The document uses inline CSS so it
 * renders identically when saved as a standalone .html file or printed.
 *
 * Pass `?format=csv` to get the original machine-readable CSV download
 * (unchanged behavior — same columns, same row order).
 *
 * The HTML layout:
 *   - Header band with club name + accent color + logo (if any)
 *   - Member name + email + generated-at timestamp
 *   - Total-hours summary tile
 *   - Bordered table with sticky header row, zebra striping, proper column widths
 *   - Footer with "Generated by ClubHub" branding
 *
 * Data logic is unchanged — same query, same fields, same ordering.
 */
export async function GET(req: Request, ctx: { params: Promise<{ clubId: string }> }) {
  const { clubId } = await ctx.params
  const c = await getClubContext(clubId)
  if (!c) return error("Not a member of this club", 403)

  const url = new URL(req.url)
  const format = (url.searchParams.get("format") ?? "html").toLowerCase()

  const items = await db.serviceHour.findMany({
    where: { clubId, userId: c.user.id, status: "approved" },
    include: {
      category: { select: { name: true } },
      reviewer: { select: { name: true } },
    },
    orderBy: [{ dateOfService: "desc" }, { submittedAt: "desc" }],
  })

  // ── CSV branch — unchanged data shape, same columns as before ──────────
  if (format === "csv") {
    const header = ["Date", "Hours", "Reason", "Category", "Reviewed By", "Reviewed At"]
    const rows: string[] = [header.join(",")]
    for (const it of items) {
      rows.push(
        [
          fmtDate(it.dateOfService),
          String(it.hours),
          csvEscape(it.reasonText),
          csvEscape(it.category?.name ?? ""),
          csvEscape(it.reviewer?.name ?? ""),
          it.reviewedAt ? fmtDateTime(it.reviewedAt) : "",
        ].join(",")
      )
    }
    const csv = rows.join("\n")
    return new Response(csv, {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="service-hours.csv"`,
        "Cache-Control": "no-store",
      },
    })
  }

  // ── HTML branch — styled, printable document ───────────────────────────
  const clubName = c.club.name
  const accent = c.club.accentColor || "#10b981"
  const memberName = c.user.name || "Member"
  const memberEmail = c.user.email
  const logoUrl = c.club.logoUrl
  const generatedAt = new Date()
  const totalHours = items.reduce((sum, it) => sum + it.hours, 0)

  const headerCols = ["Date", "Hours", "Reason", "Category", "Reviewed By", "Reviewed At"]
  const tableHeader = headerCols
    .map((h) => `<th scope="col">${htmlEscape(h)}</th>`)
    .join("")

  const tableRows = items
    .map((it, i) => {
      const rowClass = i % 2 === 0 ? "even" : "odd"
      return `<tr class="${rowClass}">
  <td class="col-date">${htmlEscape(fmtDateReadable(it.dateOfService))}</td>
  <td class="col-hours tabular">${htmlEscape(String(it.hours))}</td>
  <td class="col-reason">${htmlEscape(it.reasonText)}</td>
  <td class="col-category">${htmlEscape(it.category?.name ?? "—")}</td>
  <td class="col-reviewer">${htmlEscape(it.reviewer?.name ?? "—")}</td>
  <td class="col-reviewed-at">${it.reviewedAt ? htmlEscape(fmtDateTimeReadable(it.reviewedAt)) : "—"}</td>
</tr>`
    })
    .join("\n")

  const emptyRow =
    items.length === 0
      ? `<tr class="empty-row"><td colspan="6">No approved service hours yet.</td></tr>`
      : ""

  const logoHtml = logoUrl
    ? `<img src="${htmlEscape(logoUrl)}" alt="" class="logo" />`
    : ""

  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${htmlEscape(clubName)} — Service Hours Record</title>
  <style>
    /* Reset + base typography. Inline CSS so the doc renders identically
       when saved standalone or printed to PDF. */
    * { box-sizing: border-box; }
    html, body { margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      color: #1a1a1a;
      background: #ffffff;
      font-size: 14px;
      line-height: 1.5;
      -webkit-font-smoothing: antialiased;
      text-rendering: optimizeLegibility;
    }
    .page {
      max-width: 900px;
      margin: 0 auto;
      padding: 48px 56px;
    }
    /* Header band — club accent color strip + name + logo. Mirrors the
       app's per-club accent identity so the printed doc is on-brand. */
    .header {
      display: flex;
      align-items: center;
      gap: 16px;
      padding-bottom: 20px;
      margin-bottom: 24px;
      border-bottom: 3px solid ${accent};
    }
    .logo {
      width: 48px;
      height: 48px;
      border-radius: 12px;
      object-fit: cover;
      flex-shrink: 0;
    }
    .header-text { min-width: 0; flex: 1; }
    .club-name {
      font-size: 22px;
      font-weight: 700;
      letter-spacing: -0.01em;
      color: #111;
      margin: 0;
      line-height: 1.2;
    }
    .doc-title {
      font-size: 13px;
      color: #6b7280;
      margin: 2px 0 0 0;
      font-weight: 500;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    .accent-dot {
      display: inline-block;
      width: 8px;
      height: 8px;
      border-radius: 50%;
      background: ${accent};
      margin-right: 6px;
      vertical-align: middle;
    }
    /* Meta row — member + generated-at. */
    .meta {
      display: flex;
      flex-wrap: wrap;
      gap: 8px 24px;
      margin-bottom: 24px;
      font-size: 13px;
      color: #4b5563;
    }
    .meta-item { display: inline-flex; align-items: baseline; gap: 6px; }
    .meta-label {
      color: #9ca3af;
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      font-weight: 600;
    }
    .meta-value { color: #111; font-weight: 500; }
    /* Summary tile — total hours, big number. */
    .summary {
      display: flex;
      align-items: center;
      gap: 12px;
      background: ${accent}14;
      border: 1px solid ${accent}33;
      border-radius: 12px;
      padding: 16px 20px;
      margin-bottom: 28px;
    }
    .summary-label {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      font-weight: 600;
      color: ${accent};
    }
    .summary-value {
      font-size: 28px;
      font-weight: 700;
      color: #111;
      line-height: 1;
      font-variant-numeric: tabular-nums;
    }
    .summary-suffix {
      font-size: 13px;
      color: #6b7280;
      font-weight: 500;
      margin-left: 4px;
    }
    .summary-count {
      margin-left: auto;
      font-size: 12px;
      color: #6b7280;
    }
    /* Table — borders + zebra + sticky header. */
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 13px;
      table-layout: fixed;
    }
    thead th {
      background: #f9fafb;
      color: #374151;
      font-size: 11px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.04em;
      text-align: left;
      padding: 10px 12px;
      border: 1px solid #e5e7eb;
      border-bottom: 2px solid #d1d5db;
    }
    tbody td {
      padding: 10px 12px;
      border: 1px solid #e5e7eb;
      vertical-align: top;
      color: #1f2937;
      word-wrap: break-word;
      overflow-wrap: break-word;
    }
    tbody tr.odd td { background: #fafafa; }
    tbody tr.even td { background: #ffffff; }
    tbody tr.empty-row td {
      text-align: center;
      color: #9ca3af;
      font-style: italic;
      padding: 24px 12px;
    }
    /* Column widths — Reason gets the most space; date/hours are narrow. */
    .col-date { width: 14%; }
    .col-hours { width: 8%; text-align: right; font-weight: 600; }
    .col-reason { width: 32%; }
    .col-category { width: 14%; }
    .col-reviewer { width: 16%; }
    .col-reviewed-at { width: 16%; }
    .tabular { font-variant-numeric: tabular-nums; }
    /* Footer — branding + page hint. */
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-size: 11px;
      color: #9ca3af;
    }
    .footer-brand { font-weight: 600; color: #6b7280; }
    /* Print: tighten margins, repeat table header on each page. */
    @media print {
      body { background: #ffffff; }
      .page { max-width: none; padding: 24px 28px; }
      thead { display: table-header-group; }
      tbody tr { page-break-inside: avoid; }
      .no-print { display: none !important; }
    }
    /* Toolbar — only on screen, hidden when printing. */
    .toolbar {
      position: sticky;
      top: 0;
      z-index: 10;
      background: #ffffff;
      border-bottom: 1px solid #e5e7eb;
      padding: 12px 16px;
      display: flex;
      align-items: center;
      gap: 12px;
      justify-content: flex-end;
    }
    .toolbar button {
      font-family: inherit;
      font-size: 13px;
      font-weight: 500;
      padding: 7px 14px;
      border-radius: 8px;
      border: 1px solid #e5e7eb;
      background: #ffffff;
      color: #374151;
      cursor: pointer;
      transition: background-color 120ms ease, border-color 120ms ease;
    }
    .toolbar button:hover { background: #f9fafb; border-color: #d1d5db; }
    .toolbar button.primary {
      background: ${accent};
      color: #ffffff;
      border-color: ${accent};
    }
    .toolbar button.primary:hover { opacity: 0.9; background: ${accent}; }
    .toolbar .toolbar-spacer { flex: 1; }
    .toolbar .toolbar-hint { font-size: 12px; color: #9ca3af; }
  </style>
</head>
<body>
  <div class="toolbar no-print">
    <span class="toolbar-hint">Tip: use “Save as PDF” in the print dialog to download.</span>
    <span class="toolbar-spacer"></span>
    <button type="button" onclick="window.location.href='${htmlEscape(
      new URL(`?format=csv`, req.url).toString()
    )}'">Download CSV</button>
    <button type="button" class="primary" onclick="window.print()">Print / Save as PDF</button>
  </div>

  <div class="page">
    <header class="header">
      ${logoHtml}
      <div class="header-text">
        <h1 class="club-name"><span class="accent-dot" aria-hidden="true"></span>${htmlEscape(clubName)}</h1>
        <p class="doc-title">Service Hours Record</p>
      </div>
    </header>

    <div class="meta">
      <span class="meta-item">
        <span class="meta-label">Member</span>
        <span class="meta-value">${htmlEscape(memberName)}</span>
      </span>
      <span class="meta-item">
        <span class="meta-label">Email</span>
        <span class="meta-value">${htmlEscape(memberEmail)}</span>
      </span>
      <span class="meta-item">
        <span class="meta-label">Generated</span>
        <span class="meta-value">${htmlEscape(fmtDateTimeReadable(generatedAt))}</span>
      </span>
    </div>

    <div class="summary">
      <div>
        <div class="summary-label">Total Approved Hours</div>
        <div class="summary-value">${htmlEscape(totalHours.toFixed(1))}<span class="summary-suffix">hrs</span></div>
      </div>
      <div class="summary-count">${items.length} ${items.length === 1 ? "entry" : "entries"} · ${htmlEscape(fmtDateReadable(generatedAt))}</div>
    </div>

    <table>
      <thead>
        <tr>${tableHeader}</tr>
      </thead>
      <tbody>
        ${tableRows}
        ${emptyRow}
      </tbody>
    </table>

    <footer class="footer">
      <span class="footer-brand">Generated by ClubHub</span>
      <span>This document reflects approved service hours as of ${htmlEscape(fmtDateTimeReadable(generatedAt))}.</span>
    </footer>
  </div>
</body>
</html>`

  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "no-store",
    },
  })
}
