/**
 * Fix-up script: rewrites the TAG and ACTION inside existing catch blocks
 * generated by wrap-try-catch.ts to use the corrected derivation logic.
 *
 * For each route.ts under src/app/api/ (except signup, clubs/route.ts, nextauth),
 * finds each generated catch block and replaces the TAG and ACTION with the
 * correctly-derived values from the file path + HTTP method.
 *
 * Run with: bun run scripts/fix-catch-labels.ts
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "fs"
import { join } from "path"

const ROOT = "/home/z/my-project"
const API_ROOT = join(ROOT, "src/app/api")

const SKIP_FILES = new Set<string>([
  join(API_ROOT, "auth/signup/route.ts"),
  join(API_ROOT, "clubs/route.ts"),
  // auth/[...nextauth] has no async handlers; nothing to fix.
  join(API_ROOT, "auth/[...nextauth]/route.ts"),
])

function listRouteFiles(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    const st = statSync(full)
    if (st.isDirectory()) listRouteFiles(full, acc)
    else if (entry === "route.ts") acc.push(full)
  }
  return acc
}

function singular(s: string): string {
  if (s.endsWith("ies")) return s.slice(0, -3) + "y"
  if (s.endsWith("ses")) return s.slice(0, -2)
  if (s.endsWith("s") && !s.endsWith("ss")) return s.slice(0, -1)
  return s
}

function namedSegmentsOf(filePath: string): string[] {
  const rel = filePath.replace(API_ROOT + "/", "").replace(/\/?route\.ts$/, "")
  return rel
    .split("/")
    .filter((s) => !s.startsWith("[") && !s.startsWith("(") && s.length > 0)
}

function deriveRouteTag(filePath: string): string {
  const named = namedSegmentsOf(filePath)
  if (named.length === 0) return "root"
  return named.join("/")
}

function deriveAction(filePath: string, method: string): string {
  const rel = filePath.replace(API_ROOT + "/", "").replace(/\/?route\.ts$/, "")
  const allSegments = rel.split("/").filter((s) => s.length > 0)
  const named = namedSegmentsOf(filePath)
  if (named.length === 0) return method === "GET" ? "load resource" : "process request"
  const last = named[named.length - 1]
  const prev = named[named.length - 2] || ""
  const lastIdx = allSegments.lastIndexOf(last)
  const hasDynamicAfter = allSegments.slice(lastIdx + 1).some((s) => s.startsWith("["))

  if (last === "join") return method === "POST" ? "join club" : "process join"
  if (last === "verify-admin-passcode") return "verify admin passcode"
  if (last === "leave") return "leave club"
  if (last === "regenerate") return "regenerate club code"
  if (last === "password") return "update club password"
  if (last === "dashboard") return "load dashboard"
  if (last === "leaderboard") return "load leaderboard"
  if (last === "search") return "search club"
  if (last === "ics") return "generate calendar feed"
  if (last === "export") return "export data"
  if (last === "bulk-review") return "review hours"
  if (last === "import") return "import members"
  if (last === "urgent") return "load urgent announcements"
  if (last === "restore") return `restore ${singular(prev || "item")}`
  if (last === "read") return "mark notification read"
  if (last === "read-all") return "mark all notifications read"
  if (last === "pinned") return "load pinned messages"
  if (last === "pin") return "pin message"
  if (last === "reactions") {
    if (method === "POST") return "toggle reaction"
    if (method === "DELETE") return "remove reaction"
    return "load reactions"
  }
  if (last === "rsvp") return "RSVP to meeting"
  if (last === "attendees") return "load attendees"
  if (last === "activity") return "load activity"
  if (last === "comments") {
    if (method === "POST") return "create comment"
    if (method === "DELETE") return "delete comment"
    return "load comments"
  }
  if (last === "subtasks") {
    if (method === "POST") return "create subtask"
    if (method === "DELETE") return "delete subtask"
    return "load subtasks"
  }
  if (last === "badges") return "load badges"
  if (last === "categories") {
    if (method === "POST") return "create category"
    if (method === "PATCH" || method === "PUT") return "update category"
    if (method === "DELETE") return "delete category"
    return "load categories"
  }
  if (last === "members") {
    if (method === "POST") return "add member"
    if (method === "DELETE") return "remove member"
    return "load members"
  }
  if (last === "messages") {
    if (method === "POST") return "send message"
    if (method === "DELETE") return "delete message"
    if (hasDynamicAfter) {
      if (method === "PATCH" || method === "PUT") return "update message"
      return "load message"
    }
    return "load messages"
  }
  if (last === "conversations") {
    if (method === "POST") return "create conversation"
    if (hasDynamicAfter) {
      if (method === "PATCH" || method === "PUT") return "update conversation"
      if (method === "DELETE") return "delete conversation"
      return "load conversation"
    }
    return "load conversations"
  }
  if (last === "meetings") {
    if (method === "POST") return "create meeting"
    if (hasDynamicAfter) {
      if (method === "PATCH" || method === "PUT") return "update meeting"
      if (method === "DELETE") return "delete meeting"
      return "load meeting"
    }
    return "load meetings"
  }
  if (last === "tasks") {
    if (method === "POST") return "create task"
    if (hasDynamicAfter) {
      if (method === "PATCH" || method === "PUT") return "update task"
      if (method === "DELETE") return "delete task"
      return "load task"
    }
    return "load tasks"
  }
  if (last === "teams") {
    if (method === "POST") return "create team"
    if (hasDynamicAfter) {
      if (method === "PATCH" || method === "PUT") return "update team"
      if (method === "DELETE") return "delete team"
      return "load team"
    }
    return "load teams"
  }
  if (last === "announcements") {
    if (method === "POST") return "create announcement"
    if (hasDynamicAfter) {
      if (method === "PATCH" || method === "PUT") return "update announcement"
      if (method === "DELETE") return "delete announcement"
      return "load announcement"
    }
    return "load announcements"
  }
  if (last === "hours") {
    if (method === "POST") return "submit hours"
    if (method === "PATCH" || method === "PUT") return "review hours"
    if (hasDynamicAfter) {
      if (method === "DELETE") return "delete hours entry"
      return "load hours entry"
    }
    return "load hours"
  }
  if (last === "notifications") {
    if (method === "POST") return "create notification"
    return "load notifications"
  }
  if (last === "preferences") {
    if (method === "PATCH" || method === "PUT") return "update notification preferences"
    return "load notification preferences"
  }
  if (last === "me") {
    if (method === "PUT") return "change password"
    if (method === "PATCH") return "update profile"
    return "load user"
  }
  if (last === "clubs") {
    if (method === "POST") return "create club"
    if (hasDynamicAfter) {
      if (method === "PATCH" || method === "PUT") return "update club"
      if (method === "DELETE") return "delete club"
      return "load club"
    }
    return "load clubs"
  }
  if (last === "club") {
    if (method === "PATCH" || method === "PUT") return "update club"
    return "load club"
  }
  if (rel === "public/club/[code]" || rel === "public/club/code") return "load public club"
  if (rel === "" || rel === "route.ts") return "handle root request"

  const resource = singular(last)
  switch (method) {
    case "GET":
      return hasDynamicAfter ? `load ${resource}` : `load ${last}`
    case "POST":
      return `create ${resource}`
    case "PATCH":
    case "PUT":
      return `update ${resource}`
    case "DELETE":
      return `delete ${resource}`
    default:
      return `process ${resource}`
  }
}

const CATCH_RE =
  /  \} catch \(err: any\) \{\n    console\.error\("\[([^\]]*) (GET|POST|PATCH|PUT|DELETE)\] error:", err\?\.message, err\?\.code, err\?\.meta\)\n    return NextResponse\.json\(\{ error: "Failed to [^"]*?: " \+ \(err\?\.message \|\| "Unknown error"\) \}, \{ status: 500 \}\)\n  \}/g

function fixFile(filePath: string): { updated: number; tag: string } {
  const content = readFileSync(filePath, "utf-8")
  const tag = deriveRouteTag(filePath)
  let updated = 0
  const newContent = content.replace(CATCH_RE, (_match, _oldTag: string, method: string) => {
    updated++
    const newTag = tag
    const action = deriveAction(filePath, method)
    return (
      `  } catch (err: any) {\n` +
      `    console.error("[${newTag} ${method}] error:", err?.message, err?.code, err?.meta)\n` +
      `    return NextResponse.json({ error: "Failed to ${action}: " + (err?.message || "Unknown error") }, { status: 500 })\n` +
      `  }`
    )
  })
  if (updated > 0) writeFileSync(filePath, newContent, "utf-8")
  return { updated, tag }
}

// ---- Main ----
const files = listRouteFiles(API_ROOT).filter((f) => !SKIP_FILES.has(f))
let totalUpdated = 0
for (const f of files) {
  try {
    const r = fixFile(f)
    if (r.updated > 0) {
      console.log(`  [ok]   ${r.tag} — updated ${r.updated} catch block(s)`)
      totalUpdated += r.updated
    }
  } catch (e: any) {
    console.error(`  [ERR]  ${f}: ${e?.message}`)
  }
}
console.log(`\nDone. Total catch blocks relabeled: ${totalUpdated}`)
